title: "Qweary"
email: "qwearyblog@gmail.com"
description: "Security Researcher. Hardware Hacker. Curious mind."
baseurl: "" # root
url: "https://qweary.github.io"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag